<Solution xmlns:i="http://www.w3.org/2001/XMLSchema-instance" z:Id="i1" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/" xmlns="http://schemas.datacontract.org/2004/07/NationalInstruments.PackageBuilder.Engine">
    <Name>Battery Tester</Name>
    <SourceItems>
        <SourceItem z:Id="i2">
            <PluginConfigurationOptions />
            <RelativePath>Charge and Discharge.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i3">
            <PluginConfigurationOptions />
            <RelativePath>Charge and Discharge.lvlps</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i4">
            <PluginConfigurationOptions />
            <RelativePath>Charge and Discharge.lvproj</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i2" />
                <SourceItem z:Ref="i3" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i5">
            <PluginConfigurationOptions />
            <RelativePath>Battery Cycle Test.seq</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i4" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
    </SourceItems>
    <InputSourceItems>
        <SourceItem z:Ref="i5" />
    </InputSourceItems>
    <Distributions>
        <Distribution z:Id="i6" i:type="Package">
            <DistributionItems>
                <DistributionItem z:Id="i7" i:type="DistributionDirectoryItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\Battery Test</DestinationRelativePath>
                    <Name>Battery Test</Name>
                    <SourceItem i:nil="true" />
                </DistributionItem>
                <DistributionItem z:Id="i8" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\Battery Test\Charge and Discharge.lvlps</DestinationRelativePath>
                    <Name>Charge and Discharge.lvlps</Name>
                    <SourceItem z:Ref="i3" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i9" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\Battery Test\Battery Cycle Test.seq</DestinationRelativePath>
                    <Name>Battery Cycle Test.seq</Name>
                    <SourceItem z:Ref="i5" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i10" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\Battery Test\Charge and Discharge.lvproj</DestinationRelativePath>
                    <Name>Charge and Discharge.lvproj</Name>
                    <SourceItem z:Ref="i4" />
                    <PluginConfigurationOptions>
                        <ConfigurationOption z:Id="i11">
                            <Definition z:Id="i12">
                                <Description i:nil="true" />
                                <Name>Include all files in LabVIEW project</Name>
                            </Definition>
                            <HasDefaultValues>true</HasDefaultValues>
                            <Value z:Id="i13" i:type="BooleanConfigurationOptionValue" />
                        </ConfigurationOption>
                    </PluginConfigurationOptions>
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i14" i:type="DistributionFileItem">
                    <DestinationRelativePath>[Program Files (64-bit)]\Battery Test\Charge and Discharge.aliases</DestinationRelativePath>
                    <Name>Charge and Discharge.aliases</Name>
                    <SourceItem z:Ref="i2" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
            </DistributionItems>
            <Name>Battery Test</Name>
            <OutputDirectory>Packages</OutputDirectory>
            <PluginConfigurationOptions />
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <Architecture>windows_x64</Architecture>
            <AutoIncrementVersion>Build</AutoIncrementVersion>
            <BuildStatus z:Id="i15">
                <BuildEverSuccessful>true</BuildEverSuccessful>
                <FileName>battery-test_1.0.0.1_windows_x64.nipkg</FileName>
                <Version>1.0.0.1</Version>
            </BuildStatus>
            <CompanyName>MyCompany</CompanyName>
            <CustomExecutes />
            <DisplayName>Battery Test</DisplayName>
            <DisplayVersion>1.0.0</DisplayVersion>
            <FileName>battery-test_1.0.0.2_windows_x64.nipkg</FileName>
            <MaintainerEmail>email@mycompany.com</MaintainerEmail>
            <MaintainerName>MyCompany</MaintainerName>
            <Messages xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <PackageName>battery-test</PackageName>
            <PackageRelationships />
            <ProductName>MyProduct</ProductName>
            <Section>Application Software</Section>
            <StoreProduct>true</StoreProduct>
            <Synopsis>Tests batteries</Synopsis>
            <Version>1.0.0.2</Version>
        </Distribution>
    </Distributions>
    <Feeds />
    <DistributionGroups>
        <DistributionGroup z:Id="i16">
            <Distributions>
                <Distribution z:Ref="i6" />
            </Distributions>
            <Name>Distribution Group</Name>
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <StageDirectory>ProcessingStage</StageDirectory>
        </DistributionGroup>
    </DistributionGroups>
    <TestStandMode>true</TestStandMode>
    <PluginConfigurationOptions>
        <ConfigurationOption z:Id="i17">
            <Definition z:Id="i18">
                <Description i:nil="true" />
                <Name>TestStand Options</Name>
            </Definition>
            <HasDefaultValues>true</HasDefaultValues>
            <Value z:Id="i19" i:type="DialogConfigurationOptionValue">
                <Values>
                    <ConfigurationOptionValue z:Id="i20" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i21" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i22" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i23" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i24" i:type="StringConfigurationOptionValue">
                        <Value>SupportVIs</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i25" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i26" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i27" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i28" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i29" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i30" i:type="BooleanConfigurationOptionValue">
                        <Value>true</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i31" i:type="BooleanConfigurationOptionValue">
                        <Value>true</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i32" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i33" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i34" i:type="PathConfigurationOptionValue">
                        <RelativePath />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i35" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i36" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i37" i:type="StringConfigurationOptionValue">
                        <Value>[BootVolume]</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i38" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i39" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i40" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                </Values>
            </Value>
        </ConfigurationOption>
    </PluginConfigurationOptions>
</Solution>